### ISSUE TITLE
Unpublish?

### ISSUE THREAD

**Issue by lukeed** [danny-andrews/fly-shell#1]
Hi there,

A few of us from the Fly team are working on a fly- shell plugin, temporarily renamed to fly-exec.

Would really appreciate it if you released the name on NPM.

Thank you!

**Comment by danny-andrews** [comment]
I'd be happy to, but I'm not exactly sure how. 😳 I tried `npm unpublish fly-shell --force`, but that didn't  seem to work.

**Comment by lukeed** [comment]
Thank you so much!

Clone this repo, enter it, then unpublish. You don't need to specify the name when unpublishing

**Comment by danny-andrews** [comment]
http://blog.npmjs.org/post/141905368000/changes-to-npms-unpublish-policy. :(

**Comment by danny-andrews** [comment]
I sent them a message with a request to unpublish.

**Comment by danny-andrews** [comment]
You might want to try using a scoped package, if you don't want to wait. https://docs.npmjs.com/misc/scope

**Comment by lukeed** [comment]
Ah, I didn't know that 🤔 I'm also not in a rush. Thanks for the update!

**Comment by lukeed** [comment]
Thank you so much Danny! Really appreciate how open you were & for going out of your way to resolve this! 😀 👍
